### ISSUE TITLE
Logo is being drawn on top of the qr code

### ISSUE THREAD

**Issue by kostia1st** [Short-io/qreator#15]
**Describe the bug**
Well, I'd expect the logo to be drawn at the center, with the actual qr code floating around it.
Instead, the code itself covers the entire rect area including the center, and the logo is drawn on top of it.

**To Reproduce**
```ts
  return await getPNG(value, {
    bgColor,
    color: fgColor,
    logo,
    logoWidth: 20,
    logoHeight: 20,
    parse_url: true,
    borderRadius: 50,
    size: 100,
  });
```

**Expected behavior**
I'd expect the logo to be drawn at the center, with the actual qr code floating around it.

**Screenshots**
![chrome_CElz2KPcAq](https://github.com/user-attachments/assets/a51f15b4-afb8-422f-b36c-bb55342c30cc)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser Chrome 128
 - Version 9.3.0

**Comment by gugu** [comment]
That's how logos in QR code work - they utilize redundancy in QR code and cover part of QR code with image. If you want to hide dots partially covered by logo - feel free to send a PR for that

**Comment by kostia1st** [comment]
Alright, will try to prepare one
