### ISSUE TITLE
Add ability to set module-level spacings

### ISSUE THREAD

**Issue by kostia1st** [Short-io/qreator#17]
I want to have an option to produce a little bit spicier QR code.

There is a number of things that could be done to the current implementation, but currently I wanted to focus on the "module spacing" effect.

Simplistic implementation of the said effect looks like this
![chrome_iCwcf2p44x](https://github.com/user-attachments/assets/aef42f5a-e79b-4abd-90a0-b50d109d0fd3)
This QR has an issue though - it does not get recognized, at least by my phone (S24).

However, once you draw the "finders" as whole things without spacings between modules, it starts working OK (this is a very loose manually edited image from above)
![chrome_dFWySk3M11](https://github.com/user-attachments/assets/1fac5bf8-6b51-4397-991b-ecfedaf0a297)

I think that the rendering of the "finders" and of the rest of the QR should be separated and potentially be done differently.

@gugu So if you're OK with that direction, I might submit a PR at some point later, with "spacing" and maybe some other effects.

**Comment by gugu** [comment]
Yes, I agree. It is in my plan, but I am focused on other company-related tasks

**Comment by gugu** [comment]
Fixed in v9.5.0
